### ISSUE TITLE
unleash ignores `cargo login`

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/cargo-unleash#35]
```
Error: no upload token found, please run `cargo login` or pass `--token`
```

Even though I am logged in - token is in `~/.cargo/credentials` - and running the `cargo login`-command doesn't fix it.

**Comment by Robbepop** [comment]
fix is to run `cargo unleash em-dragons` with `--token YOUR_TOKEN`.
`YOUR_TOKEN` is found under `.cargo/credentials`.
New tokens can be generated under crates.io/me and saved to `.cargo/credentials` using `cargo login YOUR_TOKEN` after creation.
